### ISSUE TITLE
wai-saml2-0.3.0.0 test suite failure (from hackage tarball)

### ISSUE THREAD

**Issue by DanBurton** [mbg/wai-saml2#15]
Stackage runs your package's tests from the hackage tarball, not from github source. We encountered the following error running the `wai-saml2-0.3.0.0` test suite:

```
      keycloak: FAIL
        Error parsing XML file tests/data/keycloak.xml: tests/data/keycloak.xml: openBinaryFile: does not exist (No such file or directory)
        Use -p '/keycloak/' to rerun this test only.
      okta:     FAIL
        Error parsing XML file tests/data/okta.xml: tests/data/okta.xml: openBinaryFile: does not exist (No such file or directory)
        Use -p '/okta/' to rerun this test only.
```

I believe this can be resolved by adding the test xml files to `extra-source-files`

**Comment by mbg** [comment]
Thanks for reporting this and sorry I missed this in the new release. I have just pushed a commit to fix this and will create a new release for it.
