### ISSUE TITLE
No-op status code check

### ISSUE THREAD

**Issue by Philonous** [mbg/wai-saml2#32]
[`validateResponse`](https://github.com/mbg/wai-saml2/blob/51bee129a2f88770f079361aad0189b796b02abf/src/Network/Wai/SAML2/Validation.hs#L72-L74) checks that the response status is `Success`, however, there is only one status code defined: [`Success`](https://github.com/mbg/wai-saml2/blob/51bee129a2f88770f079361aad0189b796b02abf/src/Network/Wai/SAML2/StatusCode.hs#L26-L29), so the check is a no-op.

Presence of any other status code is [handled as a parse failure](https://github.com/mbg/wai-saml2/blob/51bee129a2f88770f079361aad0189b796b02abf/src/Network/Wai/SAML2/StatusCode.hs#L38-L40) instead of a validation failure. 

While this isn't directly a problem, I think it would be more consistent to parse status codes and let the validation check for success. 

* Reference to StatusCode element with well-known status codes: https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf#page=39

**Comment by mbg** [comment]
I think this point has come up previously (although I can't find the relevant comment right now), but the gist of it is that the current state of things isn't really a deliberate design decision and just a missing implementation of other status codes. So the check should indeed be during validation and not during parsing.
