### ISSUE TITLE
wai-saml2-tests: test-data/sp.pem: openBinaryFile: does not exist

### ISSUE THREAD

**Issue by juhp** [mbg/wai-saml2#4]
This broke Stackage Nightly, so allow the testsuite to fail for now.

```
Test suite failure for package wai-saml2-0.2.1.1
    wai-saml2-tests:  exited with: ExitFailure 1
Full log available at /var/stackage/work/unpack-dir/.stack-work/logs/wai-saml2-0.2.1.1-test.log

    wai-saml2-tests: test-data/sp.pem: openBinaryFile: does not exist (No such file or directory)
```

*edit*: I see the testsuite was just added

**Comment by mbg** [comment]
Apologies! The hackage upload included some local changes which it shouldn't have. I have deprecated 0.2.1.1 and uploaded 0.2.1.2 which is the same minus the (broken) test suite.
