### ISSUE TITLE
Validating SAML responses without encrypted assertions

### ISSUE THREAD

**Issue by brandon-leapyear** [mbg/wai-saml2#5]
It seems from this line that this package only supports SAML responses with encrypted assertions:

https://github.com/mbg/wai-saml2/blob/6d81ea83bd7a3c5ece0faee2db13d0be09ba8035/src/Network/Wai/SAML2/Response.hs#L65

This is further indicated by the fact that `saml2PrivateKey` is required in `SAML2Config`:

https://github.com/mbg/wai-saml2/blob/6d81ea83bd7a3c5ece0faee2db13d0be09ba8035/src/Network/Wai/SAML2/Config.hs#L27-L29

We have SAML responses with assertions that aren't encrypted, is it possible to support this use-case?

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

For what it's worth, the `hsaml2` library seems to have the right types:

https://hackage.haskell.org/package/hsaml2-0.1.1/docs/SAML2-Core.html#t:Response

Its `Response` type has a list of `PossiblyEncrypted Assertion`s.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

@mbg by assigning yourself, should I take that to mean that you're implementing this currently? We have a pretty high priority feature that needs this. How long do you expect the work to take? Should we wait for your work, or should I fork the repo and try to get it working myself?

**Comment by mbg** [comment]
Hi, thanks for opening this issue. You're right that this use case isn't currently supported, but it would be good to support it. If you urgently need this, I would recommend you try to implement it yourself since I couldn't give you an ETA for when I would get around to it. If you do, a PR which adds this functionality would be very welcome!

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Thanks for getting back so promptly! I think we have another solution in mind, so we don't need this urgently anymore. Thanks

**Comment by mbg** [comment]
Thanks to @fumieval, this has now been implemented in #18.
