### ISSUE TITLE
zlib-0.7 compatibility

### ISSUE THREAD

**Issue by ysangkok** [mbg/wai-saml2#60]
Stackage Nightly is using zlib-0.7, so wai-saml2 can't be used with the other packages. It would be nice if wai-saml2 accepted zlib-0.7.

**Comment by mbg** [comment]
Hi @ysangkok 

I updated the package on Hackage with a metadata revision to allow zlib-0.7 some time ago. So in theory that should work fine. I may have forgot to push that change to the repo itself though. I'm currently on holiday and will try to remember doing that once I'm back.

**Comment by ysangkok** [comment]
It seems that it has been bumped on both Hackage and in the repo, thank you! Not sure how I thought this was a problem.
